### ISSUE TITLE
* does not work for multiinstance counters

### ISSUE THREAD

**Issue by discoduck2x** [poxet/influxdb-collector#1]

**Comment by poxet** [comment]
That should work now by entering * as InstanceName.

**Comment by discoduck2x** [comment]
so will you build it aswell? - also does this work with influx 0.9x ? im not sure the http api is the same or not - will you make it use the new influx line protocol which should have less overhead etc?

cool that you replied so fast :)

**Comment by poxet** [comment]
I will build a new version and put it on Chocolatey, hopefully today. :)

It would be nice to get it to work with influx 0.9x as well. I will look in to that too, not sure when though.

I'm happy for all feedback, and it is good to be able to give something back to the community. If you find more issues I will try to fix them as fast as I can.
